services:
  admin:
    build: .
    ports: 
      - 80:80
    volumes:
      - ./:/var/www/html:delegated
      - ./config/nginx/default.conf:/etc/nginx/conf.d/default.conf:delegated
    tty: true
    stdin_open: true
