name: Generate HTML

on:
  push:
    branches:
      - master
    workflow_dispatch:

jobs:
  build:
    if: github.actor != 'github-actions'
    runs-on: ubuntu-latest

    steps:
      -
        name: Checkout Code
        uses: actions/checkout@v4

      -
        name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.0'

      -
        name: Run PHP script
        run: php generate.php
      
      -
        name: Commit
        run: |
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"
          git add .
          git commit -m "Publish latest"
          git push
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
