name: Generate HTML

on:
  push:
    branches:
      - master

permissions:
  contents: write

jobs:
  build:
    if: github.actor != 'github-actions'
    runs-on: ubuntu-latest

    steps:
      -
        name: Checkout Code
        uses: actions/checkout@v4

      -
        name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.2'

      -
        name: Run PHP script
        run: php compile.php

      -
        name: Debug files are in dist
        run: ls dist
      
      -
        name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./dist
#        env:
#          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
